# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e960b6692e8c66637f839293c81f9d0969b016c8fe79c94fe3f0e52f937013f4ecd54976d0d3d93ed9d7127c67de1ae0ae30154b68b59683e12775670095f622

test:
  secret_key_base: 9b5f44a14314801840790703914adab2639d88dc04a2c67caeca74c757c233ca88bfc486f529a9b589f502c13e95c09aa2988201a7ebf96ff67b212c6083a5e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
